apiVersion: v1
kind: Service
metadata:
  name: backend-feed-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: backend-feed
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
