apiVersion: v1
kind: Service
metadata:
  name: udagram-api-user
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: udagram-api-user
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
