apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: udagram-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8100
