apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: sunyi4869/reverseproxy:v4
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret
