name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: 设置 Docker
    - name: Setup Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: 登录 DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: 构建和推送 udagram-api-feed
    - name: Build and Push udagram-api-feed
      run: |
        docker build -t udagram-api-feed ./udagram-api-feed
        docker tag udagram-api-feed sunyi4869/udagram-api-feed:v1
        docker push sunyi4869/udagram-api-feed:v1

    # Step 5: 构建和推送 udagram-api-user
    - name: Build and Push udagram-api-user
      run: |
        docker build -t udagram-api-user ./udagram-api-user
        docker tag udagram-api-user sunyi4869/udagram-api-user:v1
        docker push sunyi4869/udagram-api-user:v1

    # Step 6: 构建和推送 udagram-frontend
    - name: Build and Push udagram-frontend
      run: |
        docker build -t udagram-frontend ./udagram-frontend
        docker tag udagram-frontend sunyi4869/udagram-frontend:v1
        docker push sunyi4869/udagram-frontend:v1

    # Step 7: 构建和推送 reverseproxy
    - name: Build and Push reverseproxy
      run: |
        docker build -t reverseproxy ./udagram-reverseproxy
        docker tag reverseproxy sunyi4869/reverseproxy:v1
        docker push sunyi4869/reverseproxy:v1
